### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by mr-nano** [ncase/trust#12]
Hey,

On trying to clone the repo with, 
$ git clone https://github.com/ncase/trust.git

I receive a warning, as follows:
Cloning into 'trust'...
remote: Counting objects: 856, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 856 (delta 9), reused 14 (delta 6), pack-reused 829
Receiving objects: 100% (856/856), 7.19 MiB | 441.00 KiB/s, done.
Resolving deltas: 100% (427/427), done.
Checking connectivity... done.
**warning: remote HEAD refers to nonexistent ref, unable to checkout.**

This is on a Mac OS X with git version 2.8.1

**Comment by passcod** [comment]
This is [expected git behaviour](https://public-inbox.org/git/CACQm2Y1QtKD3M6weNhGrAQSLV8hLF4pKcpHDD7iUc78aWrt6Cw@mail.gmail.com/T/#u), and a result of this repo not having a `master` branch. Simply `cd` to the folder, and run `git checkout gh-pages`.

**Comment by mr-nano** [comment]
Thanks!

Any reason in particular why the branch is not called master by default in this repo?

**Comment by ncase** [comment]
The branch is called `gh-pages` because that's what Github needs to automatically turn it into a webpage!

And I didn't add a second, backup `master` branch because, uh, I'm lazy and do not have good git practices

**Comment by swapagarwal** [comment]
@ncase I think you can change the branch used for GitHub Pages under repository settings. 😄

**Comment by ncase** [comment]
Alright, the issue's been (finally) fixed! Because I only had one branch, I couldn't use GitHub's repo settings to update the default branch... so, I had to create a new "master" branch, push that, then set the default to the "master" branch, then set the default _back_ to the "gh-pages" branch, then delete "master".

Total hack but `git clone git@github.com:ncase/trust.git` works now, without throwing the "warning: remote HEAD refers to nonexistent ref, unable to checkout" warning!
