### ISSUE TITLE
Translation to French

### ISSUE THREAD

**Issue by PierreMarieRiviere** [ncase/trust#18]
have you had it translated to French yet?

**Comment by ncase** [comment]
Thanks for asking! So, not yet. If you'd like to give translating it a try (no pressure), I just added some how-to instructions to translate this interactive! :) https://github.com/ncase/trust#how-to-translate-this-thang Good luck!

**Comment by Tloz** [comment]
Hi @devhaoy !
I'm interested to contribute to the french translation as well.
I really want to show this to my friends!

**Comment by asgard-thor** [comment]
hi, i can help too

**Comment by PierreMarieRiviere** [comment]
@Tloz  and @asgard-thor  I'm giving it a first rough shot, then will post it here so you can improve it. Sounds good?

**Comment by asgard-thor** [comment]
Ok for me

**Comment by ncase** [comment]
Ah whoops, I should have notified you all in this issue thread: @ayowel uploaded a French translation three days ago! https://ayowel.github.io/trust/ If you notice anything wrong in their version, please let them know here! https://github.com/ayowel/trust

**Comment by Ayowel** [comment]
Actually I'm the one who should apologise.

Sorry, I didn't pay attention and went with the translation without looking up the issues, which I should have. There is probably still a lot of approximations, errors and typos, so if you find the time to fix some, I'll be more than happy to merge them.

**Comment by ChameleonScales** [comment]
Hi,
I'm sure you noticed but the font used in the title and accross the game has the acute accent backwards. It reads "è" even though when I copy and paste it in a text editor it reads "é" as it should.
Can the font be fixed (with fontforge or whatever works)?
I think it's quite a pity to have a typo on the title. Makes you think all the rest is going to look like an old Google translation. You know, the kind you didn't have to pass through multiple languages in order to make a fun song out of it.
Just kidding, love your game anyway.
