### ISSUE TITLE
Translation to Arabic 

### ISSUE THREAD

**Issue by vEonz121** [ncase/trust#22]
This would help the arabic culture that i live in understand some of the trust issues that are occurring.

It would really help having this project translated to as many languages as possible.

**Comment by ncase** [comment]
Thank you, I'm honored you asked!

So, because my code is _totally not set up at all_ for right-to-left languages, and that's a bad oversight on my part, there's a lot of hacking needed to translate the game.

However, my friend Alex Clay's doing an Arabic translation, and they're 1/3 of the way through! Alex could use some help, if you're up for it -- just tweet at them: https://twitter.com/_AlexanderClay/status/893150458046541826

**Comment by vEonz121** [comment]
Thanks for the input.
I am happy to contribute.

**Comment by hamed** [comment]
I have just finished Persian translation. Persian use the same script as Arabic, so you might use that as well. It is a quick dirty hack ... 
https://github.com/hamed/trust

**Comment by MudarAljundi** [comment]
The Arabic version is almost done. I'm currently waiting on playtesters' response before I officially publish it.

However, I've encountered a problem: Arabic thumbnail not loading when link sharing. Probably an issue with github.io servers.

This is where the Arabic thumbnail is currently hosted:
https://mudaraljundi.github.io/trust/social/thumbnail.png

Possible solutions:
1) @ncase could host the Arabic thumbnail on a trustworthy server that I could link to.
2) I will revert back to the English thumbnail hosted on _ncase.me/trust_

**Results currently with the Arabic thumbnail (You may test these yourself now):**

[Twitter Debugger](https://cards-dev.twitter.com/validator)
_after typing "https://mudaraljundi.github.io/trust/"
**No image available**_

[Facebook Debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmudaraljundi.github.io%2Ftrust%2F) 
Facebook shows the arabic thumbnail in chat, but doesn't show it on all timelines.
Provided og:image could not be downloaded because **your server was too slow to respond**.

**My code:**
```
**Original code in Index.html:**
<meta itemprop="image" content="http://ncase.me/trust/social/thumbnail.png">
<meta name="twitter:image" content="http://ncase.me/trust/thumbnail.png">
<meta property="og:image" content="http://ncase.me/trust/thumbnail.png">

**I changed the thumbnail links to point to my Arabic thumbnail:**
<meta itemprop="image" content="https://mudaraljundi.github.io/trust/social/thumbnail.png">
<meta name="twitter:image" content="https://mudaraljundi.github.io/trust/thumbnail.png">
<meta property="og:image" content="https://mudaraljundi.github.io/trust/thumbnail.png">
```

**Comment by MudarAljundi** [comment]
UPDATE: Forget my previous inquiry. I've solved the issue by hosting the Arabic thumbnail on Newgrounds dump (it doesn't appear against the NG ToS, and NG already gets my $25 every year so they probably won't mind).

**Comment by MudarAljundi** [comment]
Arabic translation has been published ;)

https://mudaraljundi.github.io/trust/
https://github.com/MudarAljundi/trust

**Comment by hamed** [comment]
Congratulations!
