### ISSUE TITLE
Score 0 for cooperator with grudger and copycat.

### ISSUE THREAD

**Issue by raulsebastianmihaila** [ncase/trust#6]
My understanding is that a grudger and a copycat would always give money to a cooperator. But in this example ![bug](https://user-images.githubusercontent.com/5671355/28689439-5071c9a4-731e-11e7-9559-b1fbaf67a257.jpg) (with regular payoffs), in the second round, the cooperators end up with 0 money.

**Comment by jonathancross** [comment]
Good question.  I get the same results.
Are each player's actions based on the interactions with an _individual_ or the group?
It seems the _Grudger_ is no longer trusting the _Cooperators_ based on the actions of _Cheaters_.  Is that correct?

**Comment by jkoelling** [comment]
Based on the source (might have missed something) it looks like the peeps interact as individuals. Their memory is reset for each round of the tournament and for each pairing, so the Grudgers do not stop trusting the Cooperators. 

**The zero score is the expected result:**
Each Cooperator plays a match à 50 rounds with the 4 other Cooperators, 3 Grudgers and 1 Copycat. All of these rounds are completely cooperative and give 2 points: `50 * 8 * 2  = 800 points`.
Each Cooperator also plays a match à 50 rounds with each of the 16 Cheaters. They loose all of those rounds (-1 each) due to their naive nature: `50 * 16 * -1 = -800 points`.
**Total score for the Cooperators: `0 points`**

**Comment by raulsebastianmihaila** [comment]
@jkoelling That makes sense, thanks!
