### ISSUE TITLE
Latvian translation issue

### ISSUE THREAD

**Issue by reversedfate** [ncase/trust#95]
Current font which is used throughout the site 'FuturaHandwritten', does not support Latvian special symbols like ā, ē, ī, ū, š, č, ž, and so on, they appear in a default font which is visibly different.

![image](https://user-images.githubusercontent.com/11056229/56273086-b8d15200-6104-11e9-967e-711d86dc9e1d.png)

I will try to find an alternative font, that supports these symbols, yet looks similiar, however is it ok to change font?

**Comment by reversedfate** [comment]
Some similar fonts I found that allow the required symbols:
https://www.1001fonts.com/caveat-font.html
https://www.1001fonts.com/minya-font.html
https://www.1001fonts.com/architects-daughter-font.html
https://www.1001fonts.com/annie-use-your-telescope-font.html

**Comment by Minoru** [comment]
It's not the first time translators need to replace the font; just search for "font" on this issue tracker. Sadly, the author never responded to say if it's okay, but presumably it is, because they added translations to the main page.

We used Pangolin for [Russian translation](https://github.com/NotDotTeam/trust), by the way. Not sure if it supports the characters you need, though.

**Comment by ncase** [comment]
> Sadly, the author never responded to say if it's okay, but presumably it is, because they added translations to the main page.

@Minoru Hi, sorry I've been swamped with work on other projects so I couldn't reply earlier! But, yes, it is okay to use other fonts – thanks for checking!

**Comment by reversedfate** [comment]
Thanks, the information was sufficient to solve the font problem.
